mode: mask_refine 
weights: output/mask_refine/preact/best-epoch=22-val_f1=0.9101.ckpt
data_path: data/
output_path: output/mask_refine
experiment_name: test
size: 512
tversky_alpha: 0.2
tversky_beta: 0.8
arch: encoder_decoder
nf: 32
n_blocks: 4
lr: 0.0001
batch_size: 16
beta1: 0.9
beta2: 0.999
schedule: plateau 
plateau_patience: 4
plateau_factor: 0.1
plateau_n: 1  
early_stop_patience: 8

