mode: mask_refine # masked_refine 

data_path: ../data/
output_path: output/mask_refine
experiment_name: test

height: 512
width: 512

tversky_alpha: 0.2
tversky_beta: 0.8

arch: encoder_decoder
nf: 32
n_blocks: 4

lr: 0.001
batch_size: 16
epochs: 10
beta1: 0
beta2: 0.9
workers: 6

schedule: none # none | step | cosine
steps: [10]
step_size: 0.1