python create_text_masks.py \
--data_path ./data/ \
--batch_size 64 \
--width 256 \
--height 512 \
--dilation 2 \
--spectral_norm_d \
--spectral_norm_g \
--ngf 32 \
--ndf 32 \
--resume results/tversky_0.2/checkpoints/checkpoint_epoch46.pth.tar \
